version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: daphne -b 0.0.0.0 -p 8000 fifa_predictor.asgi:application
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=fifa_predictor.settings
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend


networks:
  backend:
  frontend:
